### ISSUE TITLE
No Cargo.lock in wasix-axum?

### ISSUE THREAD

**Issue by nash1111** [wasix-org/wasix-rust-examples#3]
It appears that the `wasix-axum` repository does not contain a `Cargo.lock` file, is there a specific reason for this? If not, it would be greatly appreciated if you could commit it. I am experiencing a compilation error with `wasix-axum`, and having the `Cargo.lock` file might resolve the issue.

**Comment by dynamite-bud** [comment]
Added the lock file: f7f773d50ea6a8e8fa10f0b664d1c08ae44f66d1
